version: '2'
services:
    loggr-app:
        image: loggr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://loggr-mysql:3306/loggr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    loggr-mysql:
        extends:
            file: mysql.yml
            service: loggr-mysql
